%%{init: {'theme': 'base', 'themeVariables': { 'primaryColor': '#ffffff', 'edgeLabelBackground': '#ffffff', 'tertiaryColor': '#ffffff', 'mainBkg': '#ffffff', 'lineColor': '#000000', 'textColor': '#000000', 'clusterBkg': '#ffffff', 'clusterBorder': '#000000'}}}%%
flowchart TD
    %% --- STYLE DEFINITIONS ---
    classDef box fill:#ffffff,stroke:#000000,stroke-width:2px,color:#000000;
    classDef diamond fill:#ffffff,stroke:#000000,stroke-width:2px,color:#000000;
    classDef startend fill:#000000,stroke:#000000,stroke-width:2px,color:#ffffff;
    classDef err fill:#ffffff,stroke:#000000,stroke-width:2px,stroke-dasharray: 5 5,color:#000000;

    %% --- SWIMLANE 1: KARYAWAN ---
    subgraph S_USER [KARYAWAN]
        direction TB
        START((Mulai)):::startend
        U1[Buka Menu Absensi]:::box
        U2[Ambil Foto Selfie]:::box
    end

    %% --- SWIMLANE 2: APLIKASI ---
    subgraph S_APP [SISTEM APLIKASI / PWA]
        direction TB
        APP_1{Sudah Izin GPS?}:::diamond
        APP_2[Ambil Koordinat]:::box
        APP_3{Cek Radius & Mock?}:::diamond
        
        APP_4[Buka Kamera]:::box
        
        APP_CONFIG{Fitur Wajah Aktif?}:::diamond
        APP_5{Cek AI Wajah?}:::diamond
        
        APP_6[Kirim Data]:::box
        
        %% Error Nodes ditaruh disini
        ERR_1(Tolak: Lokasi Palsu):::err
        ERR_2(Tolak: Wajah Blur):::err
    end

    %% --- SWIMLANE 3: SERVER ---
    subgraph S_SRV [BASIS DATA / SERVER]
        direction TB
        SRV_1[Simpan Data]:::box
        SRV_2[Kirim Notifikasi]:::box
        FINISH((Selesai)):::startend
    end

    %% --- ALUR LOGIKA UTAMA ---
    START --> U1
    U1 --> APP_1
    
    APP_1 -- Belum --> APP_1
    APP_1 -- Ya --> APP_2
    APP_2 --> APP_3
    
    %% Alur Error Lokasi (Menyamping)
    APP_3 -- Gagal --> ERR_1
    ERR_1 -.-> U1
    
    %% Alur Sukses Lokasi
    APP_3 -- Sukses --> APP_4
    APP_4 --> U2
    U2 --> APP_CONFIG
    
    %% Branching Config Wajah
    APP_CONFIG -- Tidak --> APP_6
    APP_CONFIG -- Ya --> APP_5
    
    %% Alur Error Wajah (Menyamping)
    APP_5 -- Gagal --> ERR_2
    ERR_2 -.-> U2
    
    %% Alur Final
    APP_5 -- Sukses --> APP_6
    APP_6 --> SRV_1
    SRV_1 --> SRV_2
    SRV_2 --> FINISH

    %% Styling Link
    linkStyle default stroke:#000000,stroke-width:1px;
